import type { Metadata } from 'next';
import { Cormorant_Garamond, Inter } from 'next/font/google';
import './main.css';
import Header from '../components/Header';
import Footer from '../components/Footer';

const cormorant_garamond = Cormorant_Garamond({
  variable: '--font-cormorant-garamond',
  display: 'swap',
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--font-inter',
  display: 'swap',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Yao Tsy',
  description: 'Generated by create next app',
  robots: {
    index: false,
    follow: false,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorant_garamond.variable} ${inter.variable} antialiased`}>
        <div className="wrapper">
          <Header />

          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
